import { NextRequest, NextResponse } from "next/server"

// ---------------------------------------------------------------------------
// Mock /api/auth/me
//
// Validates the Bearer token issued by /api/auth/verify and returns the
// corresponding user profile.  A real Rentar backend would verify a signed
// JWT; here we decode the base64 payload and reconstruct the profile.
// ---------------------------------------------------------------------------
export async function GET(req: NextRequest) {
  const auth = req.headers.get("authorization")
  if (!auth?.startsWith("Bearer ")) {
    return NextResponse.json({ message: "Unauthorized" }, { status: 401 })
  }

  const token = auth.slice(7)
  if (!token) {
    return NextResponse.json({ message: "Unauthorized" }, { status: 401 })
  }

  try {
    // Decode the base64 token generated by /api/auth/verify.
    // Format: base64("<publicKey>:<signedChallenge>:<timestamp>")
    const decoded = Buffer.from(token, "base64").toString("utf-8")
    const parts = decoded.split(":")

    // Demo mode tokens are prefixed with "demo:" — accept them too.
    const publicKey = parts[0] === "demo" ? parts[1] : parts[0]

    if (!publicKey || publicKey.length < 4) {
      return NextResponse.json({ message: "Invalid token" }, { status: 401 })
    }

    return NextResponse.json({
      id: `user_${publicKey.slice(0, 8)}`,
      publicKey,
      displayName: `Stellar User ${publicKey.slice(0, 6)}`,
      email: `${publicKey.slice(0, 8).toLowerCase()}@rentar.demo`,
      createdAt: new Date().toISOString(),
      kycStatus: "verified",
    })
  } catch {
    return NextResponse.json({ message: "Invalid token" }, { status: 401 })
  }
}
